# Generated by Django 4.1 on 2024-02-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Omrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stasjon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('navn', models.CharField(max_length=100)),
                ('beskrivelse', models.TextField()),
                ('koordinater', models.CharField(max_length=100)),
                ('omrade', models.ManyToManyField(related_name='stasjoner', to='vaerdata.omrade')),
            ],
        ),
        migrations.CreateModel(
            name='Klimapunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('beskrivelse', models.TextField()),
                ('koordinater', models.CharField(max_length=100)),
                ('omrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klimapunkter', to='vaerdata.omrade')),
            ],
        ),
    ]
