# Generated by Django 4.1 on 2024-02-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaerdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klimapunkt',
            name='omrade',
        ),
        migrations.RemoveField(
            model_name='stasjon',
            name='omrade',
        ),
        migrations.AddField(
            model_name='omrade',
            name='klimapunkter',
            field=models.ManyToManyField(related_name='omrader', to='vaerdata.klimapunkt'),
        ),
        migrations.AddField(
            model_name='omrade',
            name='stasjoner',
            field=models.ManyToManyField(related_name='omrader', to='vaerdata.stasjon'),
        ),
    ]
