# Generated by Django 4.1 on 2024-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaerdata', '0002_remove_klimapunkt_omrade_remove_stasjon_omrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webkamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('beskrivelse', models.TextField(blank=True)),
                ('koordinater', models.CharField(blank=True, max_length=100)),
                ('url', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='klimapunkt',
            name='beskrivelse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klimapunkt',
            name='koordinater',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='omrade',
            name='klimapunkter',
            field=models.ManyToManyField(blank=True, related_name='omrader', to='vaerdata.klimapunkt'),
        ),
        migrations.AlterField(
            model_name='omrade',
            name='stasjoner',
            field=models.ManyToManyField(blank=True, related_name='omrader', to='vaerdata.stasjon'),
        ),
        migrations.AlterField(
            model_name='stasjon',
            name='beskrivelse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stasjon',
            name='koordinater',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='omrade',
            name='webkameraer',
            field=models.ManyToManyField(blank=True, related_name='omrader', to='vaerdata.webkamera'),
        ),
    ]
