# Generated by Django 4.1 on 2024-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaerdata', '0003_webkamera_alter_klimapunkt_beskrivelse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='stasjon',
            name='sensor_elements',
            field=models.ManyToManyField(blank=True, to='vaerdata.sensor'),
        ),
    ]
