# Generated by Django 4.1 on 2024-02-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaerdata', '0004_sensor_stasjon_sensor_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='stasjon',
            name='altitude',
            field=models.IntegerField(null=True),
        ),
    ]
