# Generated by Django 4.1 on 2024-02-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaerdata', '0006_metogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrade',
            name='metogrammer',
            field=models.ManyToManyField(blank=True, related_name='omrader', to='vaerdata.metogram'),
        ),
    ]
