# Generated by Django 4.1 on 2024-02-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaerdata', '0007_omrade_metogrammer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vindrose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaerdata.stasjon')),
            ],
        ),
    ]
