# Generated by Django 4.1 on 2024-02-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaerdata', '0008_vindrose'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrade',
            name='vindroser',
            field=models.ManyToManyField(blank=True, related_name='omrader', to='vaerdata.vindrose'),
        ),
    ]
